# Get mock data from fake server
GET http://localhost:3123/api HTTP/1.1

###
HEAD /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###

GET /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###

GET http://localhost:5000 HTTP/1.1

###

GET http://localhost:5000/comments/1 HTTP/1.1

###

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatar": "torrance.png",
  "firstName": "Jack",
  "lastName": "Torrance",
  "password": "shining"
}

###
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

POST http://localhost:5000/offers
Content-Type: application/json

{
  "name": "Test place",
    "description": "test description",
    "date": "2024-04-23T15:28:07.118Z",
    "city": "Brussels",
    "preview": "https://housinganywhere.com/room/ut1254027/be/Grimbergen/lakensestraat",
    "photos": [
        "https://housinganywhere.com/room/ut1508147/be/Ixelles/rue-l-on-cuissez",
        "https://housinganywhere.com/room/ut1508147/be/Ixelles/rue-l-on-cuissez,https://www.agoda.com/three-bridges-hotel/hotel/nan-th.html?cid=1844104&ds=RJX%2FCdJedwDoPMg","https://www.agoda.com/three-bridges-hotel/hotel/nan-th.html?cid=1844104&ds=RJX%2FCdJedwDoPMgL","https://www.agoda.com/three-bridges-hotel/hotel/nan-th.html?cid=1844104&ds=RJX%2FCdJedwDoPMgL","https://www.agoda.com/three-bridges-hotel/hotel/nan-th.html?cid=1844104&ds=RJX%2FCdJedwDoPMgL","https://www.agoda.com/three-bridges-hotel/hotel/nan-th.html?cid=1844104&ds=RJX%2FCdJedwDoPMgL"
    ],
    "isPremium": true,
    "isFavorite": true,
    "rating": 5,
    "type": "room",
    "roomsCount": 1,
    "guestsCount": 5,
    "price": 57660,
    "facilities": [
        "Baby seat","Washer","Air conditioning"
    ],
    "userId": "664a1688a632baf2fa0ac9c8",
    "latitude": 4.895168,
    "longitude": 4.895168
}

###

GET http://localhost:5000/offers/664a1746d2eeb04cdd866440 HTTP/1.1

###

GET http://localhost:5000/offers HTTP/1.1

###

DELETE http://localhost:5000/offers/66671e7909adc24cdd797c78 HTTP/1.1

###

PATCH http://localhost:5000/offers/66671e1409adc24cdd797c74 HTTP/1.1
Content-Type: application/json

{
  "name": "Wonderland"
}

###

GET http://localhost:5000/offers/664a1688a632baf2fa0ac9c8/favorites HTTP/1.1

###

GET http://localhost:5000/offers/premium/Brussels HTTP/1.1

###

POST http://localhost:5000/offers/664a1688a632baf2fa0ac9c8/favorites/66671dac3687b309f87b4777 HTTP/1.1

###

POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json

{
  "offerId": "664a1746d2eeb04cdd866448",
  "text": "Face palm",
  "userId": "664a1688a632baf2fa0ac9c8"
}

###

GET http://localhost:5000/offers/664a1746d2eeb04cdd866448/comments HTTP/1.1

###

POST http://localhost:5000/offers
Content-Type: application/json

{
  "name": "M",
    "description": "test description",
    "date": "2024-04-23T15:28:07.118Z",
    "city": "Brussels",
    "preview": "https://housinganywhere.com/room/ut1254027/be/Grimbergen/lakensestraat",
    "photos": [
        "https://housinganywhere.com/room/ut1508147/be/Ixelles/rue-l-on-cuissez"

    ],
    "isPremium": true,
    "isFavorite": true,
    "rating": 10,
    "type": "room",
    "roomsCount": 1,
    "guestsCount": 5,
    "price": 57660,
    "facilities": [
        "Baby seat","TV","Air conditioning"
    ],
    "userId": "664a1688a632baf2fa0ac9c8",
    "latitude": 4.895168,
    "longitude": 4.895168
}

###

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "toransoverlook.net",
  "avatar": "torrance.png",
  "firstName": "J",
  "lastName": "T"
}

###

POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json

{
  "offerId": "664a1746d2eeb04cdd866",
  "text": "F",
  "userId": "664a1688a632baf2fa0ac9c8"
}
